{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE StrictData #-}
{-# LANGUAGE NoImplicitPrelude #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- Derived from AWS service descriptions, licensed under Apache 2.0.

-- |
-- Module      : Amazonka.BedrockRuntime.Types.ReasoningContentBlockDelta
-- Copyright   : (c) 2013-2023 Brendan Hay
-- License     : Mozilla Public License, v. 2.0.
-- Maintainer  : Brendan Hay
-- Stability   : hand-written
-- Portability : non-portable (GHC extensions)
--
-- Hand-written module: the code generator cannot render
-- @vnd.amazon.eventstream@ operations, so the @ConverseStream@ shapes are
-- maintained by hand. See @HANDWRITTEN.md@ in this package.
module Amazonka.BedrockRuntime.Types.ReasoningContentBlockDelta where

import qualified Amazonka.Core as Core
import qualified Amazonka.Core.Lens.Internal as Lens
import qualified Amazonka.Data as Data
import qualified Amazonka.Prelude as Prelude

-- | Contains content regarding the reasoning that is carried out by the
-- model with respect to the content in the content block. Reasoning refers
-- to a Chain of Thought (CoT) that the model generates to enhance the
-- accuracy of its final response.
--
-- /See:/ 'newReasoningContentBlockDelta' smart constructor.
data ReasoningContentBlockDelta = ReasoningContentBlockDelta'
  { -- | The content in the reasoning that was encrypted by the model provider
    -- for safety reasons. The encryption doesn\'t affect the quality of
    -- responses.
    redactedContent :: Prelude.Maybe Data.Base64,
    -- | A token that verifies that the reasoning text was generated by the
    -- model. If you pass a reasoning block back to the API in a multi-turn
    -- conversation, include the text and its signature unmodified.
    signature :: Prelude.Maybe Prelude.Text,
    -- | The reasoning that the model used to return the output.
    text :: Prelude.Maybe Prelude.Text
  }
  deriving (Prelude.Eq, Prelude.Show, Prelude.Generic)

-- |
-- Create a value of 'ReasoningContentBlockDelta' with all optional fields omitted.
--
-- Use <https://hackage.haskell.org/package/generic-lens generic-lens> or <https://hackage.haskell.org/package/optics optics> to modify other optional fields.
--
-- The following record fields are available, with the corresponding lenses provided
-- for backwards compatibility:
--
-- 'redactedContent', 'reasoningContentBlockDelta_redactedContent' - The content in the reasoning that was encrypted by the model provider
-- for safety reasons. The encryption doesn\'t affect the quality of
-- responses.--
-- -- /Note:/ This 'Lens' automatically encodes and decodes Base64 data.
-- -- The underlying isomorphism will encode to Base64 representation during
-- -- serialisation, and decode from Base64 representation during deserialisation.
-- -- This 'Lens' accepts and returns only raw unencoded data.
--
-- 'signature', 'reasoningContentBlockDelta_signature' - A token that verifies that the reasoning text was generated by the
-- model.
--
-- 'text', 'reasoningContentBlockDelta_text' - The reasoning that the model used to return the output.
newReasoningContentBlockDelta ::
  ReasoningContentBlockDelta
newReasoningContentBlockDelta =
  ReasoningContentBlockDelta'
    { redactedContent =
        Prelude.Nothing,
      signature = Prelude.Nothing,
      text = Prelude.Nothing
    }

-- | The content in the reasoning that was encrypted by the model provider
-- for safety reasons. The encryption doesn\'t affect the quality of
-- responses.--
-- -- /Note:/ This 'Lens' automatically encodes and decodes Base64 data.
-- -- The underlying isomorphism will encode to Base64 representation during
-- -- serialisation, and decode from Base64 representation during deserialisation.
-- -- This 'Lens' accepts and returns only raw unencoded data.
reasoningContentBlockDelta_redactedContent :: Lens.Lens' ReasoningContentBlockDelta (Prelude.Maybe Prelude.ByteString)
reasoningContentBlockDelta_redactedContent = Lens.lens (\ReasoningContentBlockDelta' {redactedContent} -> redactedContent) (\s@ReasoningContentBlockDelta' {} a -> s {redactedContent = a} :: ReasoningContentBlockDelta) Prelude.. Lens.mapping Data._Base64

-- | A token that verifies that the reasoning text was generated by the
-- model.
reasoningContentBlockDelta_signature :: Lens.Lens' ReasoningContentBlockDelta (Prelude.Maybe Prelude.Text)
reasoningContentBlockDelta_signature = Lens.lens (\ReasoningContentBlockDelta' {signature} -> signature) (\s@ReasoningContentBlockDelta' {} a -> s {signature = a} :: ReasoningContentBlockDelta)

-- | The reasoning that the model used to return the output.
reasoningContentBlockDelta_text :: Lens.Lens' ReasoningContentBlockDelta (Prelude.Maybe Prelude.Text)
reasoningContentBlockDelta_text = Lens.lens (\ReasoningContentBlockDelta' {text} -> text) (\s@ReasoningContentBlockDelta' {} a -> s {text = a} :: ReasoningContentBlockDelta)

instance Data.FromJSON ReasoningContentBlockDelta where
  parseJSON =
    Data.withObject
      "ReasoningContentBlockDelta"
      ( \x ->
          ReasoningContentBlockDelta'
            Prelude.<$> (x Data..:? "redactedContent")
            Prelude.<*> (x Data..:? "signature")
            Prelude.<*> (x Data..:? "text")
      )

instance Prelude.Hashable ReasoningContentBlockDelta where
  hashWithSalt _salt ReasoningContentBlockDelta' {..} =
    _salt
      `Prelude.hashWithSalt` redactedContent
      `Prelude.hashWithSalt` signature
      `Prelude.hashWithSalt` text

instance Prelude.NFData ReasoningContentBlockDelta where
  rnf ReasoningContentBlockDelta' {..} =
    Prelude.rnf redactedContent `Prelude.seq`
      Prelude.rnf signature `Prelude.seq`
        Prelude.rnf text
